# Intermediate SQL

Here you can access every table used in the course. To access each table, you will need to specify the `cinema` schema in your queries (e.g., `cinema.reviews` for the `reviews` table.

---
_Note: When using sample integrations such as those that contain course data, you have read-only access. You can run queries, but cannot make any changes such as adding, deleting, or modifying the data (e.g., creating tables, views, etc.)._

## Take Notes

Add notes about the concepts you've learned and SQL cells with queries you want to keep.

_Add your notes here_

In [2]:
-- Add your own queries here
SELECT *
FROM cinema.reviews
LIMIT 5

   id  film_id  num_user  num_critic  imdb_score  num_votes  facebook_likes
0   1     3934       588         432         7.1     203461           46000
1   2     3405       285         267         6.4     149998               0
2   3      478        65          29         3.2       8465             491
3   4       74        83          25         7.6       7071             930
4   5     1254      1437         224         8.0     241030           13000

In [1]:
SELECT COUNT(birthdate) AS count_birthdates
FROM cinema.people;

   count_birthdates
0              6152

In [3]:
SELECT COUNT(name) AS count_names, COUNT (birthdate) AS birth_dates
FROM cinema.people;

   count_names  birth_dates
0         8397         6152

In [4]:
SELECT DISTINCT language
FROM cinema.films

      language
0       Danish
1        Greek
2     Dzongkha
3         None
4        Tamil
5      Swahili
6     Mandarin
7         Urdu
8     Filipino
9      Bosnian
10        Maya
11       Dutch
12        Dari
13     Spanish
14    Japanese
15   Slovenian
16      Arabic
17      French
18
19      Hebrew
20     Aramaic
21   Hungarian
22        Thai
23     Kannada
24      Telugu
25       Czech
26      Kazakh
27      Korean
28   Icelandic
29      Polish
30     Russian
31     Persian
32      German
33     Italian
34     Chinese
35   Mongolian
36   Norwegian
37  Aboriginal
38  Indonesian
39     Swedish
40     Panjabi
41  Vietnamese
42   Cantonese
43  Portuguese
44       Hindi
45    Romanian
46     English
47        Zulu

In [1]:
SELECT COUNT(DISTINCT language) AS count_distinct_languages
FROM cinema.films;

   count_distinct_languages
0                        48

In [2]:
-- Count the distinct countries from the films table
SELECT COUNT(DISTINCT country) AS count_distinct_countries
FROM cinema.films;

   count_distinct_countries
0                        65

In [ ]:
-- Count the records with at least 100,000 votes
SELECT COUNT(num_votes) AS films_over_100K_votes
FROM reviews
WHERE num_votes>=100000;

In [2]:
-- Count the Spanish-language films
SELECT COUNT(language) AS count_spanish
FROM cinema.films
WHERE language = 'Spanish'

   count_spanish
0             40

In [3]:
SELECT cinema.films.title
FROM cinema.films
WHERE (cinema.films.release_year = 1994 OR cinema.films.release_year = 2000) 
		AND (cinema.films.certification = 'PG' OR cinema.films.certification = 'R');

                         title
0           3 Ninjas Kick Back
1       A Low Down Dirty Shame
2               Baby's Day Out
3        Beverly Hills Cop III
4        Bullets Over Broadway
..                         ...
125  What Planet Are You From?
126                    Whipped
127               Woman on Top
128                Wonder Boys
129        You Can Count on Me

[130 rows x 1 columns]

In [4]:
SELECT cinema.films.title
FROM cinema.films
WHERE cinema.films.release_year 
BETWEEN 1994 AND 2000 AND cinema.films.country='UK';

                            title
0     Four Weddings and a Funeral
1             The Hudsucker Proxy
2                Dead Man Walking
3                       GoldenEye
4                     Richard III
..                            ...
59                         Snatch
60                      The Claim
61                      The Claim
62             The House of Mirth
63  Thomas and the Magic Railroad

[64 rows x 1 columns]

In [1]:
SELECT cinema.films.title, cinema.films.release_year
FROM cinema.films
WHERE cinema.films.release_year BETWEEN 1990 AND 2000
	AND cinema.films.budget > 100000000
-- Amend the query to include Spanish or French-language films
	AND (cinema.films.language='Spanish' OR cinema.films.language='French');

                                     title  release_year
0  Les couloirs du temps: Les visiteurs II          1998
1                                    Tango          1998

## Explore Datasets
Use the `descriptions`, `films`, `people`, `reviews`, and `roles` tables to explore the data and practice your skills!
- Which titles in the `reviews` table have an IMDB score higher than 8.5?
- Select all titles from Germany released after 2010 from the `films` table.
- Calculate a count of all movies by country using the `films` table.

In [1]:
--- Which titles in the reviews table have an IMDB score higher than 8.5?
SELECT cinema.films.title
FROM cinema.films
JOIN cinema.reviews ON cinema.films.id = cinema.reviews.film_id
WHERE imdb_score>8.5;

                                                title
0                                        Modern Times
1                                          Casablanca
2                               It's a Wonderful Life
3                                       Seven Samurai
4                                        12 Angry Men
5                      The Good, the Bad and the Ugly
6                        Once Upon a Time in the West
7                                       The Godfather
8                              The Godfather: Part II
9                     One Flew Over the Cuckoo's Nest
10                 Star Wars: Episode IV - A New Hope
11     Star Wars: Episode V - The Empire Strikes Back
12                                         Goodfellas
13                           The Silence of the Lambs
14                                   Schindler's List
15                                       Forrest Gump
16                                       Pulp Fiction
17                           The Shawshank Redemption
18                                              Se7en
19                                 The Usual Suspects
20                                 American History X
21                                Saving Private Ryan
22                                         Fight Club
23                                         The Matrix
24                                      Spirited Away
25  The Lord of the Rings: The Fellowship of the Ring
26                                        City of God
27              The Lord of the Rings: The Two Towers
28      The Lord of the Rings: The Return of the King
29                                    The Dark Knight
30                                          Inception
31                                     Butterfly Girl
32                                       Interstellar
33                             Queen of the Mountains
34                                    Running Forever
35                        A Beginner's Guide to Snuff
36                               Kickboxer: Vengeance
37                                   The Honeymooners
38                                   Towering Inferno

In [9]:
--Select all titles from Germany released after 2010 from the films table.
SELECT cinema.films.title, cinema.films.release_year
FROM cinema.films
WHERE (cinema.films.release_year>2010) AND (cinema.films.country='Germany');

                            title  release_year
0              30 Minutes or Less          2011
1                      The Divide          2011
2            The Three Musketeers          2011
3                     Cloud Atlas          2012
4      Resident Evil: Retribution          2012
5                 Banshee Chapter          2013
6  Hansel & Gretel: Witch Hunters          2013
7                           Stung          2015

In [10]:
SELECT cinema.films.title, cinema.films.release_year
FROM cinema.films
WHERE cinema.films.release_year IN (1920, 1930, 1940)

                            title  release_year
0  Over the Hill to the Poorhouse          1920
1                   Hell's Angels          1930
2                       Boom Town          1940
3                        Fantasia          1940
4                       Pinocchio          1940
5                         Rebecca          1940
6                   The Blue Bird          1940

In [ ]:
-- Find the title and language of all films in English, Spanish, and French
SELECT title, language
FROM films
WHERE language IN ('English', 'Spanish', 'French');

-- Find the title and release_year for all films over two hours in length released in 1990 and 2000
SELECT title, release_year
FROM films
WHERE release_year IN (1990, 2000) 
    AND (duration>120);
	

-- Find the title, certification, and language all films certified NC-17 or R that are in English, Italian, or Greek
SELECT title, certification, language
FROM films
WHERE certification IN ('NC-17', 'R')
    AND language IN ('English', 'Italian', 'Greek');
	
-- Count the unique titles
SELECT COUNT(DISTINCT title) AS nineties_english_films_for_teens
FROM films
-- Filter to release_years to between 1990 and 1999
WHERE (release_year BETWEEN 1990 AND 1999)
-- Filter to English-language films
	AND (language='English')
-- Narrow it down to G, PG, and PG-13 certifications
	AND (certification ='G' OR certification ='PG' OR certification ='PG-13');